<?php

declare(strict_types=1);

// Environment / sensor telemetry (2026-09-07) - shared by the new
// /utility/environment/ page and the small live snippet on the Utility
// landing page (public/utility/index.php).
//
// WHY A SEPARATE EXPORT FROM progression-public.json: audited before
// building this (per instruction). piratebox_progression.py's
// HARDWARE_SIGNALS registry is real, but progression-public.json is
// generated by piratebox_status_helper.sh invoking piratebox_
// progression.py as a brand-new, separate CLI process every 30s - a
// fresh process whose HARDWARE_SIGNALS registry is always empty,
// since registration only happens inside the long-running OLED
// daemon's own process memory (confirmed live: that file's "hardware"
// key is permanently `{}` in production). Sensors also aren't really a
// Progression/Captain's Log concern anyway - broadening that export
// would blur a boundary that doesn't need blurring. So: a small,
// separate, narrowly-scoped export
// (/run/piratebox-sensors/sensors-public.json), written directly by
// piratebox_oled_daemon.py's own publish_sensors_export() - the one
// process that actually holds a live, rate-limited sensor reader in
// memory. See docs/OPERATIONAL-DECISIONS.md for the full writeup.
//
// PRIVACY / SPOILER BOUNDARY: this file never reads progression.json
// or progression-public.json - it has no access to achievements,
// triggers, thresholds, cooldowns, or any Progression internals, and
// cannot leak any of that by construction (there is nothing here to
// leak it FROM). It only ever reads the sensors-public.json export
// above, which itself only ever contains plain physical readings
// (currently just ambient light) - no per-visitor, per-connection, or
// admin information of any kind.
//
// SAME "honest missing value, never fabricated" discipline as every
// other live-status reader in this app (piratebox_get_helper_status(),
// piratebox_get_progression_public()): a missing/stale/malformed
// export degrades to "unavailable," never a fabricated zero or an
// unlabeled stale number presented as current.

if (!defined('PIRATEBOX_SENSORS_PUBLIC_FILE')) {
    define('PIRATEBOX_SENSORS_PUBLIC_FILE', '/run/piratebox-sensors/sensors-public.json');
}
if (!defined('PIRATEBOX_SENSORS_STALE_AFTER')) {
    // piratebox_oled_daemon.py publishes at most every ~20s
    // (SENSORS_PUBLISH_INTERVAL_S) - allow a few missed cycles before
    // treating the EXPORT ITSELF as stale (i.e. the daemon has stopped
    // publishing at all) - distinct from any one sensor's own `stale`
    // flag inside its block, which means "this reading is old" even
    // while the daemon keeps publishing fine.
    define('PIRATEBOX_SENSORS_STALE_AFTER', 90);
}

if (!function_exists('piratebox_parse_sensors_public')) {
    /**
     * Defensive parse - never trusts the decoded shape. Only string
     * keys mapping to array values survive; anything else in a
     * malformed/corrupted file is silently dropped rather than crashing
     * a page that reads it.
     *
     * @return array{sensors: array<string, array<string, mixed>>}
     */
    function piratebox_parse_sensors_public($decoded): array
    {
        $sensors = [];
        if (is_array($decoded) && is_array($decoded['sensors'] ?? null)) {
            foreach ($decoded['sensors'] as $key => $value) {
                if (is_string($key) && is_array($value)) {
                    $sensors[$key] = $value;
                }
            }
        }
        return ['sensors' => $sensors];
    }
}

if (!function_exists('piratebox_get_sensors_public')) {
    /**
     * @return array{data: array{sensors: array<string, array>}, stale: bool}
     */
    function piratebox_get_sensors_public(): array
    {
        $raw = @file_get_contents(PIRATEBOX_SENSORS_PUBLIC_FILE);
        if ($raw === false) {
            return ['data' => piratebox_parse_sensors_public(null), 'stale' => true];
        }
        $decoded = json_decode($raw, true);
        $data = piratebox_parse_sensors_public($decoded);
        $age = time() - (int) (is_array($decoded) ? ($decoded['generated_at'] ?? 0) : 0);
        return ['data' => $data, 'stale' => $age > PIRATEBOX_SENSORS_STALE_AFTER];
    }
}

// --- Ambient light classification -------------------------------------
// UI-ONLY presentation bands for the visitor-facing page. Deliberately
// independent of, and never derived from, any PirateBox Progression or
// achievement condition/threshold - these boundaries were chosen from
// ordinary, widely-published ambient-lighting reference points
// (moonlight/twilight through direct daylight), not from anything
// specific to this project's internal logic, and must never be changed
// to match one.
if (!function_exists('piratebox_classify_ambient_light')) {
    /**
     * @return array{label: string, description: string}
     */
    function piratebox_classify_ambient_light(float $lux): array
    {
        if ($lux < 10) {
            return [
                'label' => 'Dark',
                'description' => 'Very little ambient light - like a dim room at night or well after sunset.',
            ];
        }
        if ($lux < 50) {
            return [
                'label' => 'Dim',
                'description' => 'Low light - a room lit by a single lamp, or deep twilight.',
            ];
        }
        if ($lux < 250) {
            return [
                'label' => 'Indoor',
                'description' => 'Typical indoor room lighting.',
            ];
        }
        if ($lux < 1000) {
            return [
                'label' => 'Bright',
                'description' => 'Well-lit indoor space, or a shaded spot outdoors.',
            ];
        }
        return [
            'label' => 'Very Bright',
            'description' => 'Direct daylight or very bright lighting.',
        ];
    }
}

if (!function_exists('piratebox_get_ambient_light_reading')) {
    /**
     * The one place both the Utility landing page's live snippet and
     * the dedicated Environment page compute "what do we actually know
     * about the BH1750 right now" - never duplicated between them.
     *
     * @param ?array $export Injectable for tests (the exact shape
     *   piratebox_get_sensors_public() returns) - production callers
     *   always omit this and get the real live export.
     * @return array{
     *   installed: bool, available: bool, stale_export: bool,
     *   detected: bool, stale_reading: bool, lux: ?float,
     *   classification: ?array{label: string, description: string},
     *   last_success_seconds_ago: ?float
     * }
     *   `installed` - true the instant the sensor's key exists in the
     *     export at all (it was actually registered by the daemon) -
     *     this is what governs whether any Ambient Light UI appears at
     *     all; a sensor never wired stays entirely absent, never a
     *     permanent "unavailable" placeholder.
     *   `available` - true only when there is a CURRENT, trustworthy
     *     reading to show right now.
     */
    function piratebox_get_ambient_light_reading(?array $export = null): array
    {
        $export = $export ?? piratebox_get_sensors_public();
        $block = $export['data']['sensors']['ambient_light'] ?? null;
        $installed = is_array($block);
        $detected = $installed && ($block['detected'] ?? false) === true;
        $lux = ($detected && is_numeric($block['lux'] ?? null)) ? (float) $block['lux'] : null;
        $staleReading = $installed ? (bool) ($block['stale'] ?? true) : true;
        $available = $installed && !$export['stale'] && $detected && !$staleReading && $lux !== null;
        $lastSuccessSecondsAgo = ($installed && is_numeric($block['last_success_seconds_ago'] ?? null))
            ? (float) $block['last_success_seconds_ago']
            : null;

        return [
            'installed' => $installed,
            'available' => $available,
            'stale_export' => $export['stale'],
            'detected' => $detected,
            'stale_reading' => $staleReading,
            'lux' => $lux,
            'classification' => $lux !== null ? piratebox_classify_ambient_light($lux) : null,
            'last_success_seconds_ago' => $lastSuccessSecondsAgo,
        ];
    }
}
